import { Aside, Navbar } from "@/layouts";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Dashboard",
  description: "Generated by create next app",
};

export default function DashboardLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
      <Navbar />
      <main className="min-h-[90.9vh] flex">
        <Aside />
        {children}
      </main>
    </>
  );
}
